### ISSUE TITLE
[feat] #3 퀴즈, 질문, 답변, 유저선택 엔티티 생성

### ISSUE THREAD

**Issue by move-hoon** [SOPKATHON-iOS-TEAM3/Sopkathon-SERVER#3]
## Feature Issue 📌

- Quiz 엔티티를 생성합니다.
- Qusestion 엔티티를 생성합니다.
- Answer 엔티티를 생성합니다.
- UserChoice 엔티티를 생성합니다.

<br>

## Todo ✔️

- [x]  Quiz 엔티티 생성
- [x] Qusestion 엔티티 생성
- [x] Answer 엔티티 생성
- [x] UserChoice 엔티티 생성
