### ISSUE TITLE
[feat] #9 홈 화면 GET API

### ISSUE THREAD

**Issue by jun3327** [SOPKATHON-iOS-TEAM3/Sopkathon-SERVER#8]
## Feature Issue 📌
- 홈 화면 요청 시 멤버ID와 친해지고 싶은 친구 수 반환

<br>

## Todo ✔️

- [x]  홈 반환 컨트롤러 작성
- [x] 서비스 코드 작성
- [x] 멤버 엔티티에 현재 친해진 사람 수(friendShipFriend) 추가
